kind = "mobile"
previewPath = "/diseasex-mobile/"
title = "DiseaseX Mobile"
version = "1.0.0"
id = "artifacts/diseasex-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/diseasex-mobile/" ]
localPort = 24879

[services.development]
run = "pnpm --filter @workspace/diseasex-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/diseasex-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/diseasex-mobile", "run", "serve" ]

[services.env]
PORT = "24879"
BASE_PATH = "/diseasex-mobile/"
